# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Dictionary
version:      0.01
version_from: lib/WWW/Dictionary.pm
installdirs:  site
requires:
    HTML::Strip:                   0
    Test::More:                    0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
